name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        xcode: [latest, latest-stable]
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread

  linux:
    strategy:
      fail-fast: false
      matrix:
        swiftver: [swift:5.7]
        swiftos: [jammy, amazonlinux2]
    runs-on: ubuntu-latest
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests with Thread Sanitizer
        env:
          SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --enable-test-discovery --sanitize=thread