name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        xcode: [latest, latest-stable]
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1.1
        with: { 'xcode-version': '${{ matrix.xcode }}' }
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
  linux:
    strategy:
      fail-fast: false
      matrix:
        swiftver:
          - swift:5.10
        swiftos:
          - amazonlinux2
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread